/**
 * @description = it is a like base/master file which will redner for all routes
 */
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem",
        }}>
          <h3>Header</h3>
        </header>

        {children}

        <footer style={{
          backgroundColor: "LightSlateGrey",
          padding: "1rem",
        }}>

          <h3>Footer</h3>

        </footer>

      </body>
    </html>
  )
}
